apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: influxdb-sa-fms-config
  name: influxdb-sa-fms-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
