apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mosquitto-sa-fms
  name: mosquitto-sa-fms
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: mosquitto-sa-fms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mosquitto-sa-fms
    spec:
      containers:
        - image: eclipse-mosquitto_sa_fms:latest
          name: mosquitto-sa-fms
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/data
              name: mosquitto-sa-fms-data
            - mountPath: /mosquitto/log
              name: mosquitto-sa-fms-logs
      restartPolicy: Always
      volumes:
        - name: mosquitto-sa-fms-data
          persistentVolumeClaim:
            claimName: mosquitto-sa-fms-data
        - name: mosquitto-sa-fms-logs
          persistentVolumeClaim:
            claimName: mosquitto-sa-fms-logs
