apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mosquitto-sa-fms
  name: mosquitto-sa-fms
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    io.kompose.service: mosquitto-sa-fms
