apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: node-red-sa-fms
  name: node-red-sa-fms
spec:
  ports:
    - name: "1880"
      port: 1880
      targetPort: 1880
  selector:
    io.kompose.service: node-red-sa-fms
