apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: sensor-simulator-sa-fms
  name: sensor-simulator-sa-fms
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: sensor-simulator-sa-fms
