spring.application:
  name: Sensor Simulator
  version: 1.0.0

mqtt:
  broker-url: ${BROKER_PROTOCOL:tcp}://${BROKER_URL:localhost}:${BROKER_PORT:1883}
  client-id: ${MQTT_CLIENT_ID:sensor-simulator}
  username: ${BROKER_USERNAME:admin}
  password: ${BROKER_PWD:admin}
